(cl:defpackage teach_repeat-srv
  (:use )
  (:export
   "IMAGEMATCH"
   "<IMAGEMATCH-REQUEST>"
   "IMAGEMATCH-REQUEST"
   "<IMAGEMATCH-RESPONSE>"
   "IMAGEMATCH-RESPONSE"
   "SAVEIMAGEANDPOSE"
   "<SAVEIMAGEANDPOSE-REQUEST>"
   "SAVEIMAGEANDPOSE-REQUEST"
   "<SAVEIMAGEANDPOSE-RESPONSE>"
   "SAVEIMAGEANDPOSE-RESPONSE"
   "SETGOAL"
   "<SETGOAL-REQUEST>"
   "SETGOAL-REQUEST"
   "<SETGOAL-RESPONSE>"
   "SETGOAL-RESPONSE"
   "SETJOINTSTATE"
   "<SETJOINTSTATE-REQUEST>"
   "SETJOINTSTATE-REQUEST"
   "<SETJOINTSTATE-RESPONSE>"
   "SETJOINTSTATE-RESPONSE"
  ))

