// Generated by gencpp from file teach_repeat/CompressedImageSynchronised.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_COMPRESSEDIMAGESYNCHRONISED_H
#define TEACH_REPEAT_MESSAGE_COMPRESSEDIMAGESYNCHRONISED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/CompressedImage.h>

namespace teach_repeat
{
template <class ContainerAllocator>
struct CompressedImageSynchronised_
{
  typedef CompressedImageSynchronised_<ContainerAllocator> Type;

  CompressedImageSynchronised_()
    : left()
    , right()  {
    }
  CompressedImageSynchronised_(const ContainerAllocator& _alloc)
    : left(_alloc)
    , right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> const> ConstPtr;

}; // struct CompressedImageSynchronised_

typedef ::teach_repeat::CompressedImageSynchronised_<std::allocator<void> > CompressedImageSynchronised;

typedef boost::shared_ptr< ::teach_repeat::CompressedImageSynchronised > CompressedImageSynchronisedPtr;
typedef boost::shared_ptr< ::teach_repeat::CompressedImageSynchronised const> CompressedImageSynchronisedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator1> & lhs, const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator1> & lhs, const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teach_repeat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6e5e9dab29899863c78cfe4653e4f3c";
  }

  static const char* value(const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6e5e9dab2989986ULL;
  static const uint64_t static_value2 = 0x3c78cfe4653e4f3cULL;
};

template<class ContainerAllocator>
struct DataType< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teach_repeat/CompressedImageSynchronised";
  }

  static const char* value(const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/CompressedImage left\n"
"sensor_msgs/CompressedImage right\n"
"================================================================================\n"
"MSG: sensor_msgs/CompressedImage\n"
"# This message contains a compressed image\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"\n"
"string format        # Specifies the format of the data\n"
"                     #   Acceptable values:\n"
"                     #     jpeg, png\n"
"uint8[] data         # Compressed image buffer\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CompressedImageSynchronised_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teach_repeat::CompressedImageSynchronised_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_COMPRESSEDIMAGESYNCHRONISED_H
