// Generated by gencpp from file teach_repeat/ImageMatch.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_IMAGEMATCH_H
#define TEACH_REPEAT_MESSAGE_IMAGEMATCH_H

#include <ros/service_traits.h>


#include <teach_repeat/ImageMatchRequest.h>
#include <teach_repeat/ImageMatchResponse.h>


namespace teach_repeat
{

struct ImageMatch
{

typedef ImageMatchRequest Request;
typedef ImageMatchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageMatch
} // namespace teach_repeat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::teach_repeat::ImageMatch > {
  static const char* value()
  {
    return "bf90076cbd0aaa2c3002ff8e25b2d560";
  }

  static const char* value(const ::teach_repeat::ImageMatch&) { return value(); }
};

template<>
struct DataType< ::teach_repeat::ImageMatch > {
  static const char* value()
  {
    return "teach_repeat/ImageMatch";
  }

  static const char* value(const ::teach_repeat::ImageMatch&) { return value(); }
};


// service_traits::MD5Sum< ::teach_repeat::ImageMatchRequest> should match
// service_traits::MD5Sum< ::teach_repeat::ImageMatch >
template<>
struct MD5Sum< ::teach_repeat::ImageMatchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::teach_repeat::ImageMatch >::value();
  }
  static const char* value(const ::teach_repeat::ImageMatchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::teach_repeat::ImageMatchRequest> should match
// service_traits::DataType< ::teach_repeat::ImageMatch >
template<>
struct DataType< ::teach_repeat::ImageMatchRequest>
{
  static const char* value()
  {
    return DataType< ::teach_repeat::ImageMatch >::value();
  }
  static const char* value(const ::teach_repeat::ImageMatchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::teach_repeat::ImageMatchResponse> should match
// service_traits::MD5Sum< ::teach_repeat::ImageMatch >
template<>
struct MD5Sum< ::teach_repeat::ImageMatchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::teach_repeat::ImageMatch >::value();
  }
  static const char* value(const ::teach_repeat::ImageMatchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::teach_repeat::ImageMatchResponse> should match
// service_traits::DataType< ::teach_repeat::ImageMatch >
template<>
struct DataType< ::teach_repeat::ImageMatchResponse>
{
  static const char* value()
  {
    return DataType< ::teach_repeat::ImageMatch >::value();
  }
  static const char* value(const ::teach_repeat::ImageMatchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_IMAGEMATCH_H
