// Generated by gencpp from file teach_repeat/ImageMatchResponse.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_IMAGEMATCHRESPONSE_H
#define TEACH_REPEAT_MESSAGE_IMAGEMATCHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace teach_repeat
{
template <class ContainerAllocator>
struct ImageMatchResponse_
{
  typedef ImageMatchResponse_<ContainerAllocator> Type;

  ImageMatchResponse_()
    : offsets()
    , correlations()  {
    }
  ImageMatchResponse_(const ContainerAllocator& _alloc)
    : offsets(_alloc)
    , correlations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32MultiArray_<ContainerAllocator>  _offsets_type;
  _offsets_type offsets;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _correlations_type;
  _correlations_type correlations;





  typedef boost::shared_ptr< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ImageMatchResponse_

typedef ::teach_repeat::ImageMatchResponse_<std::allocator<void> > ImageMatchResponse;

typedef boost::shared_ptr< ::teach_repeat::ImageMatchResponse > ImageMatchResponsePtr;
typedef boost::shared_ptr< ::teach_repeat::ImageMatchResponse const> ImageMatchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teach_repeat::ImageMatchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teach_repeat::ImageMatchResponse_<ContainerAllocator1> & lhs, const ::teach_repeat::ImageMatchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.offsets == rhs.offsets &&
    lhs.correlations == rhs.correlations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teach_repeat::ImageMatchResponse_<ContainerAllocator1> & lhs, const ::teach_repeat::ImageMatchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teach_repeat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1edb88eeb88cf8ce0651530e66accc09";
  }

  static const char* value(const ::teach_repeat::ImageMatchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1edb88eeb88cf8ceULL;
  static const uint64_t static_value2 = 0x0651530e66accc09ULL;
};

template<class ContainerAllocator>
struct DataType< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teach_repeat/ImageMatchResponse";
  }

  static const char* value(const ::teach_repeat::ImageMatchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32MultiArray offsets\n"
"std_msgs/Float32MultiArray correlations\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int32[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
;
  }

  static const char* value(const ::teach_repeat::ImageMatchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offsets);
      stream.next(m.correlations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageMatchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teach_repeat::ImageMatchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teach_repeat::ImageMatchResponse_<ContainerAllocator>& v)
  {
    s << indent << "offsets: ";
    s << std::endl;
    Printer< ::std_msgs::Int32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.offsets);
    s << indent << "correlations: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.correlations);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_IMAGEMATCHRESPONSE_H
