// Generated by gencpp from file teach_repeat/ImageMatchRequest.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_IMAGEMATCHREQUEST_H
#define TEACH_REPEAT_MESSAGE_IMAGEMATCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <std_msgs/UInt32.h>
#include <std_msgs/UInt32.h>

namespace teach_repeat
{
template <class ContainerAllocator>
struct ImageMatchRequest_
{
  typedef ImageMatchRequest_<ContainerAllocator> Type;

  ImageMatchRequest_()
    : normalisedImage()
    , imageIndex()
    , searchRange()  {
    }
  ImageMatchRequest_(const ContainerAllocator& _alloc)
    : normalisedImage(_alloc)
    , imageIndex(_alloc)
    , searchRange(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _normalisedImage_type;
  _normalisedImage_type normalisedImage;

   typedef  ::std_msgs::UInt32_<ContainerAllocator>  _imageIndex_type;
  _imageIndex_type imageIndex;

   typedef  ::std_msgs::UInt32_<ContainerAllocator>  _searchRange_type;
  _searchRange_type searchRange;





  typedef boost::shared_ptr< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageMatchRequest_

typedef ::teach_repeat::ImageMatchRequest_<std::allocator<void> > ImageMatchRequest;

typedef boost::shared_ptr< ::teach_repeat::ImageMatchRequest > ImageMatchRequestPtr;
typedef boost::shared_ptr< ::teach_repeat::ImageMatchRequest const> ImageMatchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teach_repeat::ImageMatchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teach_repeat::ImageMatchRequest_<ContainerAllocator1> & lhs, const ::teach_repeat::ImageMatchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.normalisedImage == rhs.normalisedImage &&
    lhs.imageIndex == rhs.imageIndex &&
    lhs.searchRange == rhs.searchRange;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teach_repeat::ImageMatchRequest_<ContainerAllocator1> & lhs, const ::teach_repeat::ImageMatchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teach_repeat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8068ccda2d8b8592777c3770dade93d5";
  }

  static const char* value(const ::teach_repeat::ImageMatchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8068ccda2d8b8592ULL;
  static const uint64_t static_value2 = 0x777c3770dade93d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teach_repeat/ImageMatchRequest";
  }

  static const char* value(const ::teach_repeat::ImageMatchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image normalisedImage\n"
"std_msgs/UInt32 imageIndex\n"
"std_msgs/UInt32 searchRange # total images searched = 1 + 2*searchRange\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt32\n"
"uint32 data\n"
;
  }

  static const char* value(const ::teach_repeat::ImageMatchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.normalisedImage);
      stream.next(m.imageIndex);
      stream.next(m.searchRange);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageMatchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teach_repeat::ImageMatchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teach_repeat::ImageMatchRequest_<ContainerAllocator>& v)
  {
    s << indent << "normalisedImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.normalisedImage);
    s << indent << "imageIndex: ";
    s << std::endl;
    Printer< ::std_msgs::UInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.imageIndex);
    s << indent << "searchRange: ";
    s << std::endl;
    Printer< ::std_msgs::UInt32_<ContainerAllocator> >::stream(s, indent + "  ", v.searchRange);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_IMAGEMATCHREQUEST_H
