// Generated by gencpp from file teach_repeat/SaveImageAndPoseRequest.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSEREQUEST_H
#define TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <geometry_msgs/Pose.h>

namespace teach_repeat
{
template <class ContainerAllocator>
struct SaveImageAndPoseRequest_
{
  typedef SaveImageAndPoseRequest_<ContainerAllocator> Type;

  SaveImageAndPoseRequest_()
    : image()
    , pose()  {
    }
  SaveImageAndPoseRequest_(const ContainerAllocator& _alloc)
    : image(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveImageAndPoseRequest_

typedef ::teach_repeat::SaveImageAndPoseRequest_<std::allocator<void> > SaveImageAndPoseRequest;

typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseRequest > SaveImageAndPoseRequestPtr;
typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseRequest const> SaveImageAndPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator1> & lhs, const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image == rhs.image &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator1> & lhs, const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teach_repeat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "672da49f0f9dd60a346bf2c27f4562ba";
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x672da49f0f9dd60aULL;
  static const uint64_t static_value2 = 0x346bf2c27f4562baULL;
};

template<class ContainerAllocator>
struct DataType< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teach_repeat/SaveImageAndPoseRequest";
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveImageAndPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teach_repeat::SaveImageAndPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSEREQUEST_H
