// Generated by gencpp from file teach_repeat/SaveImageAndPoseResponse.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSERESPONSE_H
#define TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace teach_repeat
{
template <class ContainerAllocator>
struct SaveImageAndPoseResponse_
{
  typedef SaveImageAndPoseResponse_<ContainerAllocator> Type;

  SaveImageAndPoseResponse_()
    : success(false)
    , message()  {
    }
  SaveImageAndPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveImageAndPoseResponse_

typedef ::teach_repeat::SaveImageAndPoseResponse_<std::allocator<void> > SaveImageAndPoseResponse;

typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseResponse > SaveImageAndPoseResponsePtr;
typedef boost::shared_ptr< ::teach_repeat::SaveImageAndPoseResponse const> SaveImageAndPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator1> & lhs, const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator1> & lhs, const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace teach_repeat

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "teach_repeat/SaveImageAndPoseResponse";
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # indicate successful run of triggered service\n"
"string message # informational, e.g. for error messages\n"
;
  }

  static const char* value(const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveImageAndPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::teach_repeat::SaveImageAndPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_SAVEIMAGEANDPOSERESPONSE_H
