// Generated by gencpp from file teach_repeat/SetJointState.msg
// DO NOT EDIT!


#ifndef TEACH_REPEAT_MESSAGE_SETJOINTSTATE_H
#define TEACH_REPEAT_MESSAGE_SETJOINTSTATE_H

#include <ros/service_traits.h>


#include <teach_repeat/SetJointStateRequest.h>
#include <teach_repeat/SetJointStateResponse.h>


namespace teach_repeat
{

struct SetJointState
{

typedef SetJointStateRequest Request;
typedef SetJointStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointState
} // namespace teach_repeat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::teach_repeat::SetJointState > {
  static const char* value()
  {
    return "a2e5d0f6e7d0bf3763b0d5e04dd5b765";
  }

  static const char* value(const ::teach_repeat::SetJointState&) { return value(); }
};

template<>
struct DataType< ::teach_repeat::SetJointState > {
  static const char* value()
  {
    return "teach_repeat/SetJointState";
  }

  static const char* value(const ::teach_repeat::SetJointState&) { return value(); }
};


// service_traits::MD5Sum< ::teach_repeat::SetJointStateRequest> should match
// service_traits::MD5Sum< ::teach_repeat::SetJointState >
template<>
struct MD5Sum< ::teach_repeat::SetJointStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::teach_repeat::SetJointState >::value();
  }
  static const char* value(const ::teach_repeat::SetJointStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::teach_repeat::SetJointStateRequest> should match
// service_traits::DataType< ::teach_repeat::SetJointState >
template<>
struct DataType< ::teach_repeat::SetJointStateRequest>
{
  static const char* value()
  {
    return DataType< ::teach_repeat::SetJointState >::value();
  }
  static const char* value(const ::teach_repeat::SetJointStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::teach_repeat::SetJointStateResponse> should match
// service_traits::MD5Sum< ::teach_repeat::SetJointState >
template<>
struct MD5Sum< ::teach_repeat::SetJointStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::teach_repeat::SetJointState >::value();
  }
  static const char* value(const ::teach_repeat::SetJointStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::teach_repeat::SetJointStateResponse> should match
// service_traits::DataType< ::teach_repeat::SetJointState >
template<>
struct DataType< ::teach_repeat::SetJointStateResponse>
{
  static const char* value()
  {
    return DataType< ::teach_repeat::SetJointState >::value();
  }
  static const char* value(const ::teach_repeat::SetJointStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEACH_REPEAT_MESSAGE_SETJOINTSTATE_H
